version: "2"

services:
  app:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
        - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
